export const SUPABASE_DEFAULTS = {
  PROJECT_REF: 'qxakcsdaixzfttlcmnch',
  URL: 'https://qxakcsdaixzfttlcmnch.supabase.co',
  ANON_KEY:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4YWtjc2RhaXh6ZnR0bGNtbmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc1MDc3NTUsImV4cCI6MjEwMzA4Mzc1NX0.-ZrZQubMRtse3xJTIlP_a9wDI6Kf4rKfDlV_W5GS420',
  PUBLISHABLE_KEY: 'sb_publishable_zJgRu5FMM_TyKeCAmr44zw_ZrEY4zPu',
  STORAGE_BUCKET_PROOFS: 'submission-proofs',
  STORAGE_BUCKET_ASSETS: 'project-assets',
} as const;

export const APP_LIMITS = {
  MAX_PROJECT_NAME_LENGTH: 100,
  MAX_TAGLINE_LENGTH: 120,
  MIN_DESCRIPTION_LENGTH: 10,
  MAX_SHORT_DESCRIPTION_LENGTH: 300,
  MAX_TAGS_COUNT: 15,
  MAX_SCREENSHOTS_COUNT: 10,
  DEFAULT_SUBMISSION_QUOTA: 50,
  MAX_CONCURRENT_WORKER_JOBS: 10,
  DEFAULT_EXTRACTION_TIMEOUT_MS: 3000,
} as const;
