import { Directory } from '../types/entities.types.js';

export interface EnrichedDirectory extends Directory {
  traffic: string;
  linkType: 'Dofollow' | 'Nofollow';
  pricingType: 'Free' | 'Paid' | 'Free + Paid';
  description: string;
  drUpdated: string;
  submitUrl: string;
  brandColor: string;
  iconSvg?: string;
}

export const DIRECTORY_CATALOG: readonly EnrichedDirectory[] = [
  {
    id: 'reddit',
    name: 'Reddit',
    url: 'https://www.reddit.com/r/SideProject/submit',
    category: 'Community',
    domainRating: 95,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: true,
    estimatedTimeSec: 45,
    traffic: '52.0M',
    linkType: 'Nofollow',
    pricingType: 'Free',
    description: 'The front page of the internet - diverse communities (r/SideProject, r/SaaS) for indie founder launches.',
    drUpdated: 'Aug 2026',
    submitUrl: 'https://www.reddit.com/r/SideProject/submit',
    brandColor: '#FF4500',
    config: {
      formUrl: 'https://www.reddit.com/r/SideProject/submit',
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'techcrunch',
    name: 'TechCrunch',
    url: 'https://techcrunch.com/pages/contact-us/',
    category: 'Media & News',
    domainRating: 92,
    submissionType: 'assisted',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 60,
    traffic: '12.0M',
    linkType: 'Nofollow',
    pricingType: 'Paid',
    description: 'Leading technology media property, dedicated to profiling groundbreaking tech startups and news.',
    drUpdated: 'Aug 2026',
    submitUrl: 'https://techcrunch.com/pages/contact-us/',
    brandColor: '#00A562',
    config: {
      formUrl: 'https://techcrunch.com/pages/contact-us/',
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'producthunt',
    name: 'Product Hunt',
    url: 'https://www.producthunt.com/posts/new',
    category: 'Launch Platform',
    domainRating: 91,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: true,
    estimatedTimeSec: 60,
    traffic: '8.5M',
    linkType: 'Dofollow',
    pricingType: 'Free',
    description: 'The premier platform for discovering and launching innovative tech products and SaaS tools.',
    drUpdated: 'Aug 2026',
    submitUrl: 'https://www.producthunt.com/posts/new',
    brandColor: '#DA552F',
    config: {
      formUrl: 'https://www.producthunt.com/posts/new',
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'angellist',
    name: 'AngelList / Wellfound',
    url: 'https://wellfound.com/startups',
    category: 'Investor & Talent',
    domainRating: 90,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: true,
    estimatedTimeSec: 60,
    traffic: '2.8M',
    linkType: 'Dofollow',
    pricingType: 'Free + Paid',
    description: "The world's largest startup community for investments, discovery, and venture opportunities.",
    drUpdated: 'Aug 2026',
    submitUrl: 'https://wellfound.com/startups',
    brandColor: '#000000',
    config: {
      formUrl: 'https://wellfound.com/startups',
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'aboutme',
    name: 'About.me',
    url: 'https://about.me',
    category: 'Portfolio',
    domainRating: 90,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 30,
    traffic: '500K',
    linkType: 'Nofollow',
    pricingType: 'Free',
    description: 'Personal branding, product pages, and digital portfolio platform for creators.',
    drUpdated: 'Aug 2026',
    submitUrl: 'https://about.me',
    brandColor: '#2B2B2B',
    config: {
      formUrl: 'https://about.me',
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'hackernews',
    name: 'Hacker News (Show HN)',
    url: 'https://news.ycombinator.com/submit',
    category: 'Community',
    domainRating: 90,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 20,
    traffic: '4.2M',
    linkType: 'Nofollow',
    pricingType: 'Free',
    description: "Y Combinator's developer tech news and Show HN product launching community.",
    drUpdated: 'Aug 2026',
    submitUrl: 'https://news.ycombinator.com/submit',
    brandColor: '#FF6600',
    config: {
      formUrl: 'https://news.ycombinator.com/submit',
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'indiehackers',
    name: 'Indie Hackers',
    url: 'https://www.indiehackers.com/products/new',
    category: 'Community',
    domainRating: 80,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 35,
    traffic: '1.2M',
    linkType: 'Dofollow',
    pricingType: 'Free',
    description: 'Community of founders sharing milestones and building profitable digital businesses.',
    drUpdated: 'Aug 2026',
    submitUrl: 'https://www.indiehackers.com/products/new',
    brandColor: '#0E2439',
    config: {
      formUrl: 'https://www.indiehackers.com/products/new',
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'alternativeto',
    name: 'AlternativeTo',
    url: 'https://alternativeto.net/software/add/',
    category: 'General SaaS',
    domainRating: 80,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 35,
    traffic: '2.5M',
    linkType: 'Nofollow',
    pricingType: 'Free',
    description: 'Crowdsourced software recommendations and SaaS alternative suggestions.',
    drUpdated: 'Aug 2026',
    submitUrl: 'https://alternativeto.net/software/add/',
    brandColor: '#2C87F0',
    config: {
      formUrl: 'https://alternativeto.net/software/add/',
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'taaft',
    name: "There's An AI For That",
    url: 'https://theresanaiforthat.com/submit/',
    category: 'AI Tools',
    domainRating: 75,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 30,
    traffic: '120K',
    linkType: 'Dofollow',
    pricingType: 'Free',
    description: 'Comprehensive database of AI tools, agents, and autonomous applications.',
    drUpdated: 'Aug 2026',
    submitUrl: 'https://theresanaiforthat.com/submit/',
    brandColor: '#7C3AED',
    config: {
      formUrl: 'https://theresanaiforthat.com/submit/',
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'saashub',
    name: 'SaaSHub',
    url: 'https://www.saashub.com/submit',
    category: 'General SaaS',
    domainRating: 78,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 25,
    traffic: '1.2M',
    linkType: 'Dofollow',
    pricingType: 'Free',
    description: 'Software discovery platform helping consumers compare and select best tools.',
    drUpdated: 'Aug 2026',
    submitUrl: 'https://www.saashub.com/submit',
    brandColor: '#4F46E5',
    config: {
      formUrl: 'https://www.saashub.com/submit',
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'toolify',
    name: 'Toolify.ai',
    url: 'https://www.toolify.ai/submit',
    category: 'AI Tools',
    domainRating: 71,
    submissionType: 'direct_api',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 15,
    traffic: '950K',
    linkType: 'Dofollow',
    pricingType: 'Free',
    description: 'AI aggregator, prompt hub, and software discovery engine.',
    drUpdated: 'Aug 2026',
    submitUrl: 'https://www.toolify.ai/submit',
    brandColor: '#2563EB',
    config: {
      formUrl: 'https://www.toolify.ai/submit',
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'uneed',
    name: 'Uneed.best',
    url: 'https://www.uneed.best/submit',
    category: 'Startups & Tools',
    domainRating: 68,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 30,
    traffic: '250K',
    linkType: 'Dofollow',
    pricingType: 'Free',
    description: 'Curated directory of high quality startup tools updated daily.',
    drUpdated: 'Aug 2026',
    submitUrl: 'https://www.uneed.best/submit',
    brandColor: '#9333EA',
    config: {
      formUrl: 'https://www.uneed.best/submit',
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
];

export const DIRECTORY_BY_ID = new Map<string, EnrichedDirectory>(
  DIRECTORY_CATALOG.map((dir) => [dir.id, dir])
);
