import { Directory } from '../types/entities.types.js';

export const DIRECTORY_CATALOG: readonly Directory[] = [
  {
    id: 'alternativeto',
    name: 'AlternativeTo',
    url: 'https://alternativeto.net',
    category: 'General SaaS',
    domainRating: 81,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 35,
    config: {
      formUrl: 'https://alternativeto.net/software/add/',
      requiresLicense: true,
      supportsTags: true,
      maxTags: 8,
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'saashub',
    name: 'SaaSHub',
    url: 'https://www.saashub.com',
    category: 'General SaaS',
    domainRating: 76,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 25,
    config: {
      formUrl: 'https://www.saashub.com/submit',
      requiresPricing: true,
      supportsTags: true,
      maxTags: 5,
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'toolify',
    name: 'Toolify.ai',
    url: 'https://www.toolify.ai',
    category: 'AI Tools',
    domainRating: 73,
    submissionType: 'direct_api',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 10,
    config: {
      apiEndpoint: 'https://api.toolify.ai/v1/submit',
      authType: 'bearer',
      requiresFeatures: true,
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'uneed',
    name: 'Uneed.best',
    url: 'https://www.uneed.best',
    category: 'Startups & Tools',
    domainRating: 68,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 30,
    config: {
      formUrl: 'https://www.uneed.best/submit',
      supportsTags: true,
      maxTags: 5,
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'theresanaiforthat',
    name: "There's An AI For That (TAAFT)",
    url: 'https://theresanaiforthat.com',
    category: 'AI Tools',
    domainRating: 79,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 40,
    config: {
      formUrl: 'https://theresanaiforthat.com/submit',
      requiresFeatures: true,
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'indiehackers',
    name: 'Indie Hackers Products',
    url: 'https://www.indiehackers.com',
    category: 'Startups',
    domainRating: 83,
    submissionType: 'form_automation',
    status: 'active',
    requiresAuth: false,
    estimatedTimeSec: 30,
    config: {
      formUrl: 'https://www.indiehackers.com/products/new',
      requiresPricing: false,
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'producthunt',
    name: 'Product Hunt Upcoming',
    url: 'https://www.producthunt.com',
    category: 'Launch Platform',
    domainRating: 91,
    submissionType: 'assisted',
    status: 'active',
    requiresAuth: true,
    estimatedTimeSec: 45,
    config: {
      formUrl: 'https://www.producthunt.com/posts/new',
      requiresOAuth: true,
    },
    createdAt: '2026-08-23T00:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
];

export const DIRECTORY_BY_ID = new Map<string, Directory>(
  DIRECTORY_CATALOG.map((dir) => [dir.id, dir])
);
